[tool.poetry]
name = "stratification-app"
version = "4.1.0"
description = ""
authors = ["Nick Gill <nick@sortitionfoundation.org>", "Brett Hennig <brett@sortitionfoundation.org>", "Paul Goelz <mail@paulgoelz.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
eel = "^0.17.0"
cvxpy = "^1.5.3"
gspread = "^6.1.2"
mip = "^1.15.0"
toml = "^0.10.2"
oauth2client = "^4.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
