name: Release Executables
on:
  push:
    tags:
      - '*'

jobs:
  #
  # 1. Build Windows Executable
  #
  build-windows-exe:
    name: 'script.exe creation using python 3.11 on Windows'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # https://hynek.me/articles/python-github-actions/
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install argparse
          pip install pyinstaller==6.10.0
          pip install eel==0.17.0
          pip install cvxpy==1.5.3
          pip install gspread==6.1.2
          pip install mip
          pip install oauth2client==4.1.3
          pip install toml==0.10.2
          python -m eel script.py web -n strat-select-win.exe --additional-hooks-dir=. --onefile --noconsole
          mkdir -p target/release
          mv dist/strat-select-win.exe target/release
      # copy nicks-script.exe to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-win.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
  #
  # 2. Build MacOS Executable
  #
  build-macos-executable:
    name: 'script.app creation using python 3.11 on MacOS'
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # https://hynek.me/articles/python-github-actions/
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install argparse
          pip install pyinstaller==6.10.0
          pip install eel==0.17.0
          pip install cvxpy==1.5.3
          pip install gspread==6.1.2
          pip install mip
          pip install oauth2client==4.1.3
          pip install toml==0.10.2
          python -m eel script.py web -n strat-select-macos --additional-hooks-dir=. --onefile --noconsole
          mkdir -p target/release
          mv dist/strat-select-macos target/release
      # copy script.app to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-macos
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
  #
  # 3. Build Linux Executable
  #
  build-linux-executable:
    name: 'executable creation using python 3.11 on Linux'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # https://hynek.me/articles/python-github-actions/
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install argparse
          pip install pyinstaller==6.10.0
          pip install eel==0.17.0
          pip install cvxpy==1.5.3
          pip install gspread==6.1.2
          pip install mip
          pip install oauth2client==4.1.3
          pip install toml==0.10.2
          python -m eel script.py web -n strat-select-linux --additional-hooks-dir=. --onefile --noconsole
          mkdir -p target/release
          mv dist/strat-select-linux target/release
      # copy script.app to the release
      #
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: upload exectuable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/strat-select-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "script release text"
